#!/bin/bash

: ${BACKUP_DIR="/backups"}
: ${TIMEOUT=86400} # 24 hours

[ -d "$BACKUP_DIR" ] || mkdir -p "$BACKUP_DIR"

push_metrics() {
  [ -z "$PUSHGATEWAY" ] && return
  curl --data-binary @- "$PUSHGATEWAY"
}

backup() {
  echo "[=] $1"
  while true
  do
    echo "$1: Backup"
    /docker-backup/docker-backup $OPTS -addr /docker.sock store "$BACKUP_DIR/$1.tar" "$1" | push_metrics
    gzip "$BACKUP_DIR/$1.tar"

    date +"last_run{container=\"$1\"} %s" | push_metrics
    echo "$1: Sleep"
    sleep $TIMEOUT
  done
}

for container in $@
do
  backup $container &
done

wait
